In [1]:
# import tensorflow
import tensorflow as tf

/Users/rajsingh/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
# create tensors
hello = tf.constant("Hello")
world = tf.constant("World")

# need to start a session in order to use tensorflow
# using the 'with' keyword makes it so we don't need
# to close the session ourself
with tf.Session() as sess:
    result = sess.run(hello+world)
print(result)

HelloWorld


In [5]:
# can also fill tensor with values
# as with numpy
fill_mat = tf.fill((4,4),16)

In [6]:
# fill with zeros
myzeroes = tf.zeros((4,4))

In [7]:
# fill with random values (normal dist)
myrandn = tf.random_normal((4,4))

# fill with random values (uniform dist)
myrandu = tf.random_uniform((4,4),maxval=1.0)

In [9]:
# make list of operations so we can use them
my_operations = [fill_mat,myzeroes,myrandn,myrandu]

In [10]:
# can run an interactive session as well
# allows us to do this outside a typical
# tensorflow session
# typically don't do this though
interactive_sess = tf.InteractiveSession()

# let's actually perform these operations
# and see the tensors that we create
for operation in my_operations:
    print(interactive_sess.run(operation))
    print("\n")

[[16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]
 [16 16 16 16]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-0.01546793  0.9236789   1.6658556  -1.1414561 ]
 [ 0.2680923   1.6192477  -1.0187005  -0.6476716 ]
 [-0.6823614   0.83595747 -0.46629617 -0.29216915]
 [ 1.9651921  -0.41016597 -0.01930806 -1.967744  ]]


[[0.6019888  0.9707557  0.45937216 0.905669  ]
 [0.17182505 0.19396293 0.43696332 0.08529413]
 [0.38552594 0.47631097 0.58429575 0.42248762]
 [0.44977534 0.31454444 0.31966293 0.9460387 ]]


